[package]
name = "spotfiy_downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
rspotify = "0.12.0"
dotenvy = "0.15"
indicatif = "0.17"
colored = "2.0"
tokio = { version = "1", features = ["full"] }
